[[redirects]]
  from = "/bowie-house-application"
  to = "https://planningaccess.bromley.gov.uk/s/detail/a0lTv000003WPnxIAG"

[[redirects]]
  from = "/bowiehouseapplication"
  to = "https://planningaccess.bromley.gov.uk/s/detail/a0lTv000003WPnxIAG"

[[redirects]]
  from "/bowie-house-template-letter"
  to = "https://docs.google.com/document/d/1MZQeFDSQoE-h5Rxd1CojAUGCrN8ov8ons2pr-1lY7C0"

[[redirects]]
  from = "/bowiehousetemplateletter"
  to = "https://docs.google.com/document/d/1MZQeFDSQoE-h5Rxd1CojAUGCrN8ov8ons2pr-1lY7C0"
